# Generated by Django 6.0.3 on 2026-05-09 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.TextField()),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Wrong Answer", "Wrong Answer"),
                            ("Compilation Error", "Compilation Error"),
                            ("Runtime Error", "Runtime Error"),
                            ("Time Limit Exceeded", "Time Limit Exceeded"),
                        ],
                        max_length=40,
                    ),
                ),
                ("execution_time", models.FloatField(default=0)),
                (
                    "failed_test_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
