# Generated by Django 6.0.3 on 2026-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="memory_usage",
            field=models.PositiveIntegerField(
                default=0, help_text="Peak memory usage in KB"
            ),
        ),
    ]
