"""Seed a professional competitive-programming problem library.

This command is data-only. It does not change the judge, models, routes, or UI.
The existing Problem model has no separate explanation or memory_limit fields,
so those values are stored inside the visible statement/constraints text.
"""

import json
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from problems.models import Problem, TestCase


PROBLEM_LIBRARY = [
    {
        "title": "Sum of Two Numbers",
        "slug": "sum-of-two-numbers",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 100,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given two integers A and B, print their sum.",
        "input_format": "A single line containing two space-separated integers A and B.",
        "output_format": "Print one integer, the sum of A and B.",
        "constraints": "-10^9 <= A, B <= 10^9",
        "sample_input": "2 3",
        "sample_output": "5",
        "explanation": "2 + 3 equals 5.",
        "cases": [
            {"input": "2 3", "output": "5", "hidden": False},
            {"input": "-4 10", "output": "6"},
            {"input": "1000000000 1000000000", "output": "2000000000"},
        ],
    },
    {
        "title": "Reverse String",
        "slug": "reverse-string",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 100,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given a string S, print the characters of S in reverse order.",
        "input_format": "A single line containing string S.",
        "output_format": "Print the reversed string.",
        "constraints": "1 <= length of S <= 100000\nS may contain lowercase letters and spaces.",
        "sample_input": "codesentinel",
        "sample_output": "lenitnesedoc",
        "explanation": "Reading the sample string from right to left gives lenitnesedoc.",
        "cases": [
            {"input": "codesentinel", "output": "lenitnesedoc", "hidden": False},
            {"input": "hello", "output": "olleh"},
            {"input": "a", "output": "a"},
        ],
    },
    {
        "title": "Palindrome Check",
        "slug": "palindrome-check",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 120,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given a string S, print YES if it is a palindrome, otherwise print NO.",
        "input_format": "A single string S.",
        "output_format": "Print YES or NO.",
        "constraints": "1 <= length of S <= 100000\nS contains lowercase English letters.",
        "sample_input": "level",
        "sample_output": "YES",
        "explanation": "The string level reads the same from left to right and right to left.",
        "cases": [
            {"input": "level", "output": "YES", "hidden": False},
            {"input": "codesentinel", "output": "NO"},
            {"input": "abba", "output": "YES"},
        ],
    },
    {
        "title": "Count Vowels",
        "slug": "count-vowels",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 100,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Count how many vowels appear in the given string. Treat uppercase and lowercase vowels as equal.",
        "input_format": "A single line containing string S.",
        "output_format": "Print the number of vowels in S.",
        "constraints": "1 <= length of S <= 100000",
        "sample_input": "CodeSentinel",
        "sample_output": "5",
        "explanation": "The vowels are o, e, e, i, and e.",
        "cases": [
            {"input": "CodeSentinel", "output": "5", "hidden": False},
            {"input": "rhythm", "output": "0"},
            {"input": "AEIOUaeiou", "output": "10"},
        ],
    },
    {
        "title": "Maximum in Array",
        "slug": "maximum-in-array",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 100,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given an array of integers, print the largest element.",
        "input_format": "First line contains N. Second line contains N integers.",
        "output_format": "Print the maximum element.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "5\n1 9 3 7 2",
        "sample_output": "9",
        "explanation": "9 is greater than every other element in the array.",
        "cases": [
            {"input": "5\n1 9 3 7 2", "output": "9", "hidden": False},
            {"input": "4\n-10 -3 -7 -1", "output": "-1"},
            {"input": "1\n42", "output": "42"},
        ],
    },
    {
        "title": "Second Largest Element",
        "slug": "second-largest-element",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 120,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given an array, print the second largest distinct value. If it does not exist, print -1.",
        "input_format": "First line contains N. Second line contains N integers.",
        "output_format": "Print the second largest distinct value or -1.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "5\n4 1 7 7 3",
        "sample_output": "4",
        "explanation": "The distinct values are 1, 3, 4, and 7. The second largest is 4.",
        "cases": [
            {"input": "5\n4 1 7 7 3", "output": "4", "hidden": False},
            {"input": "4\n5 5 5 5", "output": "-1"},
            {"input": "6\n-1 -2 -3 -4 -5 -6", "output": "-2"},
        ],
    },
    {
        "title": "Even Odd Count",
        "slug": "even-odd-count",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 100,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Count how many numbers in an array are even and how many are odd.",
        "input_format": "First line contains N. Second line contains N integers.",
        "output_format": "Print two integers: even_count odd_count.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "6\n1 2 3 4 5 6",
        "sample_output": "3 3",
        "explanation": "2, 4, and 6 are even. 1, 3, and 5 are odd.",
        "cases": [
            {"input": "6\n1 2 3 4 5 6", "output": "3 3", "hidden": False},
            {"input": "5\n2 4 6 8 10", "output": "5 0"},
            {"input": "3\n-1 0 7", "output": "1 2"},
        ],
    },
    {
        "title": "Linear Search",
        "slug": "linear-search",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 100,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Find the first occurrence of X in an array. Print its 0-based index, or -1 if X is absent.",
        "input_format": "First line contains N. Second line contains N integers. Third line contains X.",
        "output_format": "Print the first index of X or -1.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai, X <= 10^9",
        "sample_input": "5\n4 8 15 16 23\n15",
        "sample_output": "2",
        "explanation": "15 appears first at index 2.",
        "cases": [
            {"input": "5\n4 8 15 16 23\n15", "output": "2", "hidden": False},
            {"input": "4\n1 2 3 4\n9", "output": "-1"},
            {"input": "5\n7 7 7 7 7\n7", "output": "0"},
        ],
    },
    {
        "title": "Fibonacci Number",
        "slug": "fibonacci-number",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 120,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given N, print the N-th Fibonacci number where F(0) = 0 and F(1) = 1.",
        "input_format": "A single integer N.",
        "output_format": "Print F(N).",
        "constraints": "0 <= N <= 45",
        "sample_input": "7",
        "sample_output": "13",
        "explanation": "The sequence starts 0, 1, 1, 2, 3, 5, 8, 13.",
        "cases": [
            {"input": "7", "output": "13", "hidden": False},
            {"input": "0", "output": "0"},
            {"input": "45", "output": "1134903170"},
        ],
    },
    {
        "title": "Prime Check",
        "slug": "prime-check",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 120,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given an integer N, print YES if N is prime, otherwise print NO.",
        "input_format": "A single integer N.",
        "output_format": "Print YES or NO.",
        "constraints": "1 <= N <= 10^9",
        "sample_input": "29",
        "sample_output": "YES",
        "explanation": "29 has no divisors other than 1 and itself.",
        "cases": [
            {"input": "29", "output": "YES", "hidden": False},
            {"input": "1", "output": "NO"},
            {"input": "1000000007", "output": "YES"},
        ],
    },
    {
        "title": "GCD of Two Numbers",
        "slug": "gcd-of-two-numbers",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 110,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given two positive integers A and B, print their greatest common divisor.",
        "input_format": "A single line containing A and B.",
        "output_format": "Print gcd(A, B).",
        "constraints": "1 <= A, B <= 10^9",
        "sample_input": "24 36",
        "sample_output": "12",
        "explanation": "12 is the largest integer that divides both 24 and 36.",
        "cases": [
            {"input": "24 36", "output": "12", "hidden": False},
            {"input": "17 31", "output": "1"},
            {"input": "1000000000 500000000", "output": "500000000"},
        ],
    },
    {
        "title": "LCM of Two Numbers",
        "slug": "lcm-of-two-numbers",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 110,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given two positive integers A and B, print their least common multiple.",
        "input_format": "A single line containing A and B.",
        "output_format": "Print lcm(A, B).",
        "constraints": "1 <= A, B <= 10^9\nThe answer fits in 64-bit signed integer range.",
        "sample_input": "12 18",
        "sample_output": "36",
        "explanation": "36 is the smallest positive integer divisible by both 12 and 18.",
        "cases": [
            {"input": "12 18", "output": "36", "hidden": False},
            {"input": "13 17", "output": "221"},
            {"input": "100000 10", "output": "100000"},
        ],
    },
    {
        "title": "Array Sum",
        "slug": "array-sum",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 100,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given an array of N integers, print the sum of all elements.",
        "input_format": "First line contains N. Second line contains N integers.",
        "output_format": "Print the total sum.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "5\n1 2 3 4 5",
        "sample_output": "15",
        "explanation": "1 + 2 + 3 + 4 + 5 equals 15.",
        "cases": [
            {"input": "5\n1 2 3 4 5", "output": "15", "hidden": False},
            {"input": "3\n-5 10 -2", "output": "3"},
            {"input": "1\n999", "output": "999"},
        ],
    },
    {
        "title": "Merge Sorted Arrays",
        "slug": "merge-sorted-arrays",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 140,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given two sorted arrays, merge them into one sorted array.",
        "input_format": "First line contains N and M. Second line contains N integers. Third line contains M integers.",
        "output_format": "Print the merged sorted array.",
        "constraints": "1 <= N, M <= 100000\n-10^9 <= values <= 10^9",
        "sample_input": "3 4\n1 4 7\n2 3 6 8",
        "sample_output": "1 2 3 4 6 7 8",
        "explanation": "The output contains all values from both arrays in nondecreasing order.",
        "cases": [
            {"input": "3 4\n1 4 7\n2 3 6 8", "output": "1 2 3 4 6 7 8", "hidden": False},
            {"input": "2 2\n1 1\n1 2", "output": "1 1 1 2"},
            {"input": "1 3\n5\n-1 0 9", "output": "-1 0 5 9"},
        ],
    },
    {
        "title": "Remove Duplicates from Sorted Array",
        "slug": "remove-duplicates-from-sorted-array",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 130,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given a sorted array, print each distinct element exactly once.",
        "input_format": "First line contains N. Second line contains N sorted integers.",
        "output_format": "Print the unique elements in sorted order.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "7\n1 1 2 2 2 3 4",
        "sample_output": "1 2 3 4",
        "explanation": "Repeated copies are removed while the original sorted order is preserved.",
        "cases": [
            {"input": "7\n1 1 2 2 2 3 4", "output": "1 2 3 4", "hidden": False},
            {"input": "4\n5 5 5 5", "output": "5"},
            {"input": "5\n-3 -2 -2 0 0", "output": "-3 -2 0"},
        ],
    },
    {
        "title": "Valid Parentheses",
        "slug": "valid-parentheses",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 150,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given a string containing brackets (), {}, and [], determine whether every bracket is closed in the correct order.",
        "input_format": "A single string S containing bracket characters.",
        "output_format": "Print YES if S is valid, otherwise print NO.",
        "constraints": "1 <= length of S <= 100000",
        "sample_input": "({[]})",
        "sample_output": "YES",
        "explanation": "Every opening bracket is closed by the matching bracket in the correct order.",
        "cases": [
            {"input": "({[]})", "output": "YES", "hidden": False},
            {"input": "(]", "output": "NO"},
            {"input": "((()))", "output": "YES"},
        ],
    },
    {
        "title": "Power Function",
        "slug": "power-function",
        "difficulty": Problem.DIFFICULTY_EASY,
        "points": 140,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Compute A raised to the power B modulo 1000000007. This is a good place to use a reusable helper function.",
        "input_format": "A single line containing A and B.",
        "output_format": "Print (A^B) modulo 1000000007.",
        "constraints": "0 <= A <= 10^9\n0 <= B <= 10^9",
        "sample_input": "2 10",
        "sample_output": "1024",
        "explanation": "2^10 equals 1024.",
        "cases": [
            {"input": "2 10", "output": "1024", "hidden": False},
            {"input": "5 0", "output": "1"},
            {"input": "2 100", "output": "976371285"},
        ],
    },
    {
        "title": "Factorial Modulo",
        "slug": "factorial-modulo",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 180,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given an integer N, print N! modulo 1000000007.",
        "input_format": "A single integer N.",
        "output_format": "Print N! modulo 1000000007.",
        "constraints": "0 <= N <= 100000",
        "sample_input": "5",
        "sample_output": "120",
        "explanation": "5! = 5 x 4 x 3 x 2 x 1 = 120.",
        "cases": [
            {"input": "5", "output": "120", "hidden": False},
            {"input": "0", "output": "1"},
            {"input": "10", "output": "3628800"},
            {"input": "100000", "output": "457992974"},
        ],
    },
    {
        "title": "Binary Search",
        "slug": "binary-search",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 180,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given a sorted array and a target X, find the 0-based index of X using efficient searching.",
        "input_format": "First line contains N. Second line contains N sorted integers. Third line contains X.",
        "output_format": "Print the index of X, or -1 if X is not present.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai, X <= 10^9",
        "sample_input": "6\n1 3 5 7 9 11\n7",
        "sample_output": "3",
        "explanation": "The value 7 is stored at index 3.",
        "cases": [
            {"input": "6\n1 3 5 7 9 11\n7", "output": "3", "hidden": False},
            {"input": "5\n2 4 6 8 10\n1", "output": "-1"},
            {"input": "1\n99\n99", "output": "0"},
        ],
    },
    {
        "title": "Two Sum Indices",
        "slug": "two-sum-indices",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 200,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given an array and a target, print the lexicographically smallest pair of indices i j such that i < j and Ai + Aj = target.",
        "input_format": "First line contains N and target. Second line contains N integers.",
        "output_format": "Print i j, or -1 if no valid pair exists.",
        "constraints": "2 <= N <= 100000\n-10^9 <= Ai, target <= 10^9",
        "sample_input": "5 9\n2 7 11 15 1",
        "sample_output": "0 1",
        "explanation": "A[0] + A[1] = 2 + 7 = 9.",
        "cases": [
            {"input": "5 9\n2 7 11 15 1", "output": "0 1", "hidden": False},
            {"input": "4 6\n3 2 4 3", "output": "0 3"},
            {"input": "3 100\n1 2 3", "output": "-1"},
        ],
    },
    {
        "title": "Kadane Maximum Subarray",
        "slug": "kadane-maximum-subarray",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 220,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Find the maximum possible sum of a non-empty contiguous subarray.",
        "input_format": "First line contains N. Second line contains N integers.",
        "output_format": "Print the maximum subarray sum.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "9\n-2 1 -3 4 -1 2 1 -5 4",
        "sample_output": "6",
        "explanation": "The subarray 4 -1 2 1 has sum 6.",
        "cases": [
            {"input": "9\n-2 1 -3 4 -1 2 1 -5 4", "output": "6", "hidden": False},
            {"input": "3\n-5 -2 -8", "output": "-2"},
            {"input": "5\n1 2 3 4 5", "output": "15"},
        ],
    },
    {
        "title": "Rotate Array",
        "slug": "rotate-array",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 180,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Rotate an array to the right by K positions.",
        "input_format": "First line contains N and K. Second line contains N integers.",
        "output_format": "Print the rotated array.",
        "constraints": "1 <= N <= 100000\n0 <= K <= 10^9",
        "sample_input": "5 2\n1 2 3 4 5",
        "sample_output": "4 5 1 2 3",
        "explanation": "After two right rotations, the last two elements move to the front.",
        "cases": [
            {"input": "5 2\n1 2 3 4 5", "output": "4 5 1 2 3", "hidden": False},
            {"input": "4 4\n9 8 7 6", "output": "9 8 7 6"},
            {"input": "3 5\n1 2 3", "output": "2 3 1"},
        ],
    },
    {
        "title": "Sort Colors",
        "slug": "sort-colors",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 190,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given an array containing only 0, 1, and 2, sort it in nondecreasing order.",
        "input_format": "First line contains N. Second line contains N integers, each 0, 1, or 2.",
        "output_format": "Print the sorted array.",
        "constraints": "1 <= N <= 100000\nAi is one of 0, 1, 2",
        "sample_input": "6\n2 0 2 1 1 0",
        "sample_output": "0 0 1 1 2 2",
        "explanation": "All 0s come first, followed by 1s and then 2s.",
        "cases": [
            {"input": "6\n2 0 2 1 1 0", "output": "0 0 1 1 2 2", "hidden": False},
            {"input": "3\n1 1 1", "output": "1 1 1"},
            {"input": "5\n2 2 0 0 1", "output": "0 0 1 2 2"},
        ],
    },
    {
        "title": "Prefix Sum Queries",
        "slug": "prefix-sum-queries",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 220,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Answer multiple range sum queries on an array. Each query asks for the sum from L to R using 1-based indices.",
        "input_format": "First line contains N and Q. Second line contains N integers. Next Q lines contain L and R.",
        "output_format": "Print one answer per query.",
        "constraints": "1 <= N, Q <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "5 3\n1 2 3 4 5\n1 3\n2 5\n4 4",
        "sample_output": "6\n14\n4",
        "explanation": "The first query sums 1 + 2 + 3 = 6.",
        "cases": [
            {"input": "5 3\n1 2 3 4 5\n1 3\n2 5\n4 4", "output": "6\n14\n4", "hidden": False},
            {"input": "3 2\n-1 5 2\n1 2\n2 3", "output": "4\n7"},
            {"input": "1 1\n99\n1 1", "output": "99"},
        ],
    },
    {
        "title": "Matrix Diagonal Sum",
        "slug": "matrix-diagonal-sum",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 180,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given an N x N matrix, print the sum of both diagonals. If N is odd, count the center cell only once.",
        "input_format": "First line contains N. Next N lines contain N integers each.",
        "output_format": "Print the diagonal sum.",
        "constraints": "1 <= N <= 500\n-10^6 <= cell value <= 10^6",
        "sample_input": "3\n1 2 3\n4 5 6\n7 8 9",
        "sample_output": "25",
        "explanation": "Primary diagonal is 1+5+9 and secondary is 3+5+7. Subtract center 5 once.",
        "cases": [
            {"input": "3\n1 2 3\n4 5 6\n7 8 9", "output": "25", "hidden": False},
            {"input": "2\n1 2\n3 4", "output": "10"},
            {"input": "1\n7", "output": "7"},
        ],
    },
    {
        "title": "Longest Common Prefix",
        "slug": "longest-common-prefix",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 180,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Given N strings, print their longest common prefix. If no common prefix exists, print EMPTY.",
        "input_format": "First line contains N. Next N lines contain one string each.",
        "output_format": "Print the longest common prefix or EMPTY.",
        "constraints": "1 <= N <= 10000\n1 <= length of each string <= 1000",
        "sample_input": "3\nflower\nflow\nflight",
        "sample_output": "fl",
        "explanation": "All three strings start with fl.",
        "cases": [
            {"input": "3\nflower\nflow\nflight", "output": "fl", "hidden": False},
            {"input": "3\ndog\nracecar\ncar", "output": "EMPTY"},
            {"input": "2\ninterview\ninternet", "output": "inte"},
        ],
    },
    {
        "title": "Next Greater Element",
        "slug": "next-greater-element",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 230,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "For every element in the array, print the first greater element to its right. If none exists, print -1.",
        "input_format": "First line contains N. Second line contains N integers.",
        "output_format": "Print N integers representing next greater elements.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "4\n4 5 2 25",
        "sample_output": "5 25 25 -1",
        "explanation": "The next greater element for 4 is 5, and for 5 and 2 it is 25.",
        "cases": [
            {"input": "4\n4 5 2 25", "output": "5 25 25 -1", "hidden": False},
            {"input": "4\n13 7 6 12", "output": "-1 12 12 -1"},
            {"input": "3\n1 2 3", "output": "2 3 -1"},
        ],
    },
    {
        "title": "Frequency Counter",
        "slug": "frequency-counter",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 190,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "Count the frequency of every distinct integer. Print pairs in increasing order of the integer.",
        "input_format": "First line contains N. Second line contains N integers.",
        "output_format": "Print pairs as value:count separated by spaces.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "6\n2 1 2 3 2 1",
        "sample_output": "1:2 2:3 3:1",
        "explanation": "1 appears twice, 2 appears three times, and 3 appears once.",
        "cases": [
            {"input": "6\n2 1 2 3 2 1", "output": "1:2 2:3 3:1", "hidden": False},
            {"input": "4\n-1 -1 0 2", "output": "-1:2 0:1 2:1"},
            {"input": "3\n5 5 5", "output": "5:3"},
        ],
    },
    {
        "title": "Climbing Stairs",
        "slug": "climbing-stairs",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 200,
        "time_limit": 2,
        "memory_limit": 128,
        "description": "You can climb either 1 or 2 steps at a time. Given N stairs, print the number of distinct ways to reach the top modulo 1000000007.",
        "input_format": "A single integer N.",
        "output_format": "Print the number of ways modulo 1000000007.",
        "constraints": "0 <= N <= 1000000",
        "sample_input": "5",
        "sample_output": "8",
        "explanation": "There are 8 valid step sequences for 5 stairs.",
        "cases": [
            {"input": "5", "output": "8", "hidden": False},
            {"input": "0", "output": "1"},
            {"input": "50", "output": "365010934"},
        ],
    },
    {
        "title": "Coin Change Minimum Coins",
        "slug": "coin-change-minimum-coins",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 260,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given coin denominations and an amount, find the minimum number of coins needed to make that amount. If impossible, print -1.",
        "input_format": "First line contains N and amount. Second line contains N coin values.",
        "output_format": "Print the minimum number of coins, or -1.",
        "constraints": "1 <= N <= 100\n0 <= amount <= 10000\n1 <= coin value <= 10000",
        "sample_input": "3 11\n1 2 5",
        "sample_output": "3",
        "explanation": "11 can be made using 5 + 5 + 1.",
        "cases": [
            {"input": "3 11\n1 2 5", "output": "3", "hidden": False},
            {"input": "1 3\n2", "output": "-1"},
            {"input": "4 27\n2 5 10 20", "output": "4"},
        ],
    },
    {
        "title": "Merge Intervals",
        "slug": "merge-intervals",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 240,
        "time_limit": 2,
        "memory_limit": 256,
        "description": "Given N intervals, merge all overlapping intervals and print the resulting intervals sorted by start.",
        "input_format": "First line contains N. Next N lines contain start and end.",
        "output_format": "Print each merged interval on a new line as start end.",
        "constraints": "1 <= N <= 100000\n-10^9 <= start <= end <= 10^9",
        "sample_input": "4\n1 3\n2 6\n8 10\n15 18",
        "sample_output": "1 6\n8 10\n15 18",
        "explanation": "Intervals [1,3] and [2,6] overlap, so they merge into [1,6].",
        "cases": [
            {"input": "4\n1 3\n2 6\n8 10\n15 18", "output": "1 6\n8 10\n15 18", "hidden": False},
            {"input": "2\n1 4\n4 5", "output": "1 5"},
            {"input": "3\n5 7\n1 2\n3 4", "output": "1 2\n3 4\n5 7"},
        ],
    },
    {
        "title": "Longest Substring Without Repeating Characters",
        "slug": "longest-substring-without-repeating-characters",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 260,
        "time_limit": 2,
        "memory_limit": 256,
        "description": "Given a string S, find the length of the longest substring that contains no repeated characters.",
        "input_format": "A single string S.",
        "output_format": "Print the maximum length.",
        "constraints": "1 <= length of S <= 100000",
        "sample_input": "abcabcbb",
        "sample_output": "3",
        "explanation": "The substring abc has length 3 and contains no repeated characters.",
        "cases": [
            {"input": "abcabcbb", "output": "3", "hidden": False},
            {"input": "bbbbb", "output": "1"},
            {"input": "pwwkew", "output": "3"},
        ],
    },
    {
        "title": "BFS Traversal",
        "slug": "bfs-traversal",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 260,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given an undirected graph and a start node, print the BFS traversal. When multiple neighbors are available, visit them in increasing order.",
        "input_format": "First line contains N and M. Next M lines contain edges u v. Last line contains start node S.",
        "output_format": "Print the BFS order.",
        "constraints": "1 <= N <= 100000\n0 <= M <= 200000\n1 <= u, v, S <= N",
        "sample_input": "5 4\n1 2\n1 3\n2 4\n3 5\n1",
        "sample_output": "1 2 3 4 5",
        "explanation": "BFS visits all nodes at distance 1 before nodes at distance 2.",
        "cases": [
            {"input": "5 4\n1 2\n1 3\n2 4\n3 5\n1", "output": "1 2 3 4 5", "hidden": False},
            {"input": "4 2\n1 2\n3 4\n3", "output": "3 4"},
            {"input": "6 5\n1 2\n1 3\n2 5\n3 4\n4 6\n1", "output": "1 2 3 5 4 6"},
        ],
    },
    {
        "title": "DFS Traversal",
        "slug": "dfs-traversal",
        "difficulty": Problem.DIFFICULTY_MEDIUM,
        "points": 260,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given an undirected graph and a start node, print the DFS preorder traversal. Visit neighbors in increasing order.",
        "input_format": "First line contains N and M. Next M lines contain edges u v. Last line contains start node S.",
        "output_format": "Print the DFS preorder.",
        "constraints": "1 <= N <= 100000\n0 <= M <= 200000\n1 <= u, v, S <= N",
        "sample_input": "5 4\n1 2\n1 3\n2 4\n3 5\n1",
        "sample_output": "1 2 4 3 5",
        "explanation": "DFS goes as deep as possible through the smallest unvisited neighbor first.",
        "cases": [
            {"input": "5 4\n1 2\n1 3\n2 4\n3 5\n1", "output": "1 2 4 3 5", "hidden": False},
            {"input": "4 2\n1 2\n3 4\n3", "output": "3 4"},
            {"input": "6 5\n1 2\n1 3\n2 5\n3 4\n4 6\n1", "output": "1 2 5 3 4 6"},
        ],
    },
    {
        "title": "Longest Increasing Subsequence",
        "slug": "longest-increasing-subsequence",
        "difficulty": Problem.DIFFICULTY_HARD,
        "points": 320,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given an array, print the length of the longest strictly increasing subsequence.",
        "input_format": "First line contains N. Second line contains N integers.",
        "output_format": "Print the LIS length.",
        "constraints": "1 <= N <= 100000\n-10^9 <= Ai <= 10^9",
        "sample_input": "8\n10 9 2 5 3 7 101 18",
        "sample_output": "4",
        "explanation": "One longest increasing subsequence is 2, 3, 7, 101.",
        "cases": [
            {"input": "8\n10 9 2 5 3 7 101 18", "output": "4", "hidden": False},
            {"input": "6\n0 1 0 3 2 3", "output": "4"},
            {"input": "5\n5 4 3 2 1", "output": "1"},
        ],
    },
    {
        "title": "0-1 Knapsack",
        "slug": "0-1-knapsack",
        "difficulty": Problem.DIFFICULTY_HARD,
        "points": 340,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given item weights and values, choose a subset with total weight at most W and maximum total value. Each item can be used at most once.",
        "input_format": "First line contains N and W. Second line contains N weights. Third line contains N values.",
        "output_format": "Print the maximum achievable value.",
        "constraints": "1 <= N <= 200\n1 <= W <= 10000\n1 <= weight, value <= 100000",
        "sample_input": "4 7\n1 3 4 5\n1 4 5 7",
        "sample_output": "9",
        "explanation": "Choose items with weights 3 and 4 for value 4 + 5 = 9.",
        "cases": [
            {"input": "4 7\n1 3 4 5\n1 4 5 7", "output": "9", "hidden": False},
            {"input": "3 50\n10 20 30\n60 100 120", "output": "220"},
            {"input": "2 3\n4 5\n10 20", "output": "0"},
        ],
    },
    {
        "title": "Edit Distance",
        "slug": "edit-distance",
        "difficulty": Problem.DIFFICULTY_HARD,
        "points": 360,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given two strings, compute the minimum number of insertions, deletions, and replacements required to convert the first string into the second.",
        "input_format": "First line contains string A. Second line contains string B.",
        "output_format": "Print the edit distance.",
        "constraints": "1 <= length of A, B <= 1000",
        "sample_input": "horse\nros",
        "sample_output": "3",
        "explanation": "horse can be converted to ros in three operations.",
        "cases": [
            {"input": "horse\nros", "output": "3", "hidden": False},
            {"input": "intention\nexecution", "output": "5"},
            {"input": "abc\nabc", "output": "0"},
        ],
    },
    {
        "title": "Number of Islands",
        "slug": "number-of-islands",
        "difficulty": Problem.DIFFICULTY_HARD,
        "points": 340,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given a grid of 0s and 1s, count connected groups of 1s. Cells are connected vertically and horizontally.",
        "input_format": "First line contains N and M. Next N lines contain M characters, each 0 or 1.",
        "output_format": "Print the number of islands.",
        "constraints": "1 <= N, M <= 1000",
        "sample_input": "4 5\n11000\n11000\n00100\n00011",
        "sample_output": "3",
        "explanation": "The grid contains three separated connected components of land.",
        "cases": [
            {"input": "4 5\n11000\n11000\n00100\n00011", "output": "3", "hidden": False},
            {"input": "3 3\n111\n010\n111", "output": "1"},
            {"input": "2 4\n0000\n0000", "output": "0"},
        ],
    },
    {
        "title": "Dijkstra Shortest Path",
        "slug": "dijkstra-shortest-path",
        "difficulty": Problem.DIFFICULTY_HARD,
        "points": 380,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given a directed weighted graph with non-negative weights, print shortest distances from source S to every node. Print INF for unreachable nodes.",
        "input_format": "First line contains N and M. Next M lines contain u v w. Last line contains source S.",
        "output_format": "Print N values: distance to nodes 1 through N.",
        "constraints": "1 <= N <= 100000\n0 <= M <= 200000\n0 <= w <= 10^9",
        "sample_input": "5 6\n1 2 2\n1 3 5\n2 3 1\n2 4 2\n3 5 3\n4 5 1\n1",
        "sample_output": "0 2 3 4 5",
        "explanation": "The shortest path from 1 to 5 is 1 -> 2 -> 4 -> 5 with cost 5.",
        "cases": [
            {"input": "5 6\n1 2 2\n1 3 5\n2 3 1\n2 4 2\n3 5 3\n4 5 1\n1", "output": "0 2 3 4 5", "hidden": False},
            {"input": "4 2\n1 2 7\n3 4 1\n1", "output": "0 7 INF INF"},
            {"input": "3 3\n1 2 4\n1 3 1\n3 2 1\n1", "output": "0 2 1"},
        ],
    },
    {
        "title": "Aggressive Cows",
        "slug": "aggressive-cows",
        "difficulty": Problem.DIFFICULTY_HARD,
        "points": 340,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given stall positions and C cows, place all cows so the minimum distance between any two cows is as large as possible.",
        "input_format": "First line contains N and C. Second line contains N stall positions.",
        "output_format": "Print the largest possible minimum distance.",
        "constraints": "2 <= C <= N <= 100000\n0 <= stall position <= 10^9",
        "sample_input": "5 3\n1 2 8 4 9",
        "sample_output": "3",
        "explanation": "Place cows at positions 1, 4, and 8 or 1, 4, and 9 for minimum distance 3.",
        "cases": [
            {"input": "5 3\n1 2 8 4 9", "output": "3", "hidden": False},
            {"input": "5 2\n4 2 1 3 6", "output": "5"},
            {"input": "6 4\n0 3 4 7 10 9", "output": "3"},
        ],
    },
    {
        "title": "Minimum Spanning Tree",
        "slug": "minimum-spanning-tree",
        "difficulty": Problem.DIFFICULTY_HARD,
        "points": 380,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given a connected undirected weighted graph, print the total weight of its minimum spanning tree.",
        "input_format": "First line contains N and M. Next M lines contain u v w.",
        "output_format": "Print the MST total weight.",
        "constraints": "1 <= N <= 100000\nN - 1 <= M <= 200000\n1 <= w <= 10^9",
        "sample_input": "4 5\n1 2 10\n1 3 6\n1 4 5\n2 4 15\n3 4 4",
        "sample_output": "19",
        "explanation": "Choose edges with weights 4, 5, and 10 for total 19.",
        "cases": [
            {"input": "4 5\n1 2 10\n1 3 6\n1 4 5\n2 4 15\n3 4 4", "output": "19", "hidden": False},
            {"input": "3 3\n1 2 1\n2 3 2\n1 3 4", "output": "3"},
            {"input": "1 0", "output": "0"},
        ],
    },
    {
        "title": "Longest Common Subsequence",
        "slug": "longest-common-subsequence",
        "difficulty": Problem.DIFFICULTY_HARD,
        "points": 360,
        "time_limit": 3,
        "memory_limit": 256,
        "description": "Given two strings, print the length of their longest common subsequence.",
        "input_format": "First line contains string A. Second line contains string B.",
        "output_format": "Print the LCS length.",
        "constraints": "1 <= length of A, B <= 1000",
        "sample_input": "abcde\nace",
        "sample_output": "3",
        "explanation": "ace is a common subsequence of length 3.",
        "cases": [
            {"input": "abcde\nace", "output": "3", "hidden": False},
            {"input": "abc\nabc", "output": "3"},
            {"input": "abc\ndef", "output": "0"},
        ],
    },
]


class Command(BaseCommand):
    help = "Create or update a rich CodeSentinel problem library with hidden test cases."

    def add_arguments(self, parser):
        parser.add_argument(
            "--from-json",
            dest="from_json",
            help="Optional path to a JSON file containing problem definitions in the same format as the built-in library.",
        )

    def handle(self, *args, **options):
        problem_definitions = self._load_definitions(options.get("from_json"))
        touched = 0
        for definition in problem_definitions:
            self._seed_problem(definition)
            touched += 1

        self.stdout.write(self.style.SUCCESS(f"Problem library ready. Problems touched: {touched}"))

    def _load_definitions(self, json_path):
        if not json_path:
            return PROBLEM_LIBRARY

        path = Path(json_path)
        if not path.exists():
            raise CommandError(f"JSON file not found: {path}")

        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise CommandError(f"Invalid JSON: {exc}") from exc

        if not isinstance(data, list):
            raise CommandError("Problem JSON must contain a list of problem objects.")
        return data

    def _seed_problem(self, definition):
        required_keys = {
            "title",
            "slug",
            "difficulty",
            "points",
            "time_limit",
            "memory_limit",
            "description",
            "input_format",
            "output_format",
            "constraints",
            "sample_input",
            "sample_output",
            "explanation",
            "cases",
        }
        missing = required_keys.difference(definition)
        if missing:
            raise CommandError(f"{definition.get('title', 'Unknown problem')} is missing: {', '.join(sorted(missing))}")

        problem, _created = Problem.objects.update_or_create(
            slug=definition["slug"],
            defaults={
                "title": definition["title"],
                "statement": self._statement(definition),
                "input_format": definition["input_format"],
                "output_format": definition["output_format"],
                "constraints": self._constraints(definition),
                "sample_input": definition["sample_input"],
                "sample_output": definition["sample_output"],
                "difficulty": definition["difficulty"],
                "time_limit": definition["time_limit"],
                "points": definition["points"],
                "is_active": True,
            },
        )
        self._replace_cases(problem, definition["cases"])

    def _statement(self, definition):
        return f"{definition['description']}\n\nSample explanation:\n{definition['explanation']}"

    def _constraints(self, definition):
        return f"{definition['constraints']}\nMemory limit: {definition['memory_limit']} MB"

    def _replace_cases(self, problem, cases):
        if not cases:
            raise CommandError(f"{problem.title} must include at least one test case.")

        problem.test_cases.all().delete()
        for index, case in enumerate(cases, start=1):
            TestCase.objects.create(
                problem=problem,
                order=index,
                input_data=case.get("input", ""),
                expected_output=case["output"],
                is_hidden=case.get("hidden", True),
            )
